mixed-port: 7890
unified-delay: false
geodata-mode: true
tcp-concurrent: false
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: true
mode: rule
log-level: info
ipv6: true

external-controller: 127.0.0.1:9090

geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: false
  sniff:
    TLS:
      ports: [443]
    HTTP:
      ports: [80]
      override-destination: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 'tls://8.8.4.4#DNS_Proxy'
    - 'tls://1.0.0.1#DNS_Proxy'
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query#h3=true
  nameserver-policy:
    "geosite:cn,private":
      - 223.5.5.5
      - 114.114.114.114
      - https://dns.alidns.com/dns-query#h3=true

proxies:
  - name: "vless_tcp_vision"
    type: vless
    server: {{ conf.user.domain }}
    port: 443
    uuid: {{ conf.user.vless }}
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
  - name: "vless_ws"
    type: vless
    server: {{ conf.user.domain }}
    port: 443
    uuid: {{ conf.user.vless }}
    udp: true
    tls: true
    network: ws
    client-fingerprint: chrome
    servername: {{ conf.user.domain }}
    ws-opts:
      path: /skws
      headers:
        Host: {{ conf.user.domain }}
  - name: "vless_grpc"
    type: vless
    server: {{ conf.user.domain }}
    port: 443
    uuid: {{ conf.user.vless }}
    udp: true
    tls: true
    network: grpc
    client-fingerprint: chrome
    servername: {{ conf.user.domain }}
    grpc-opts:
      grpc-service-name: skgrpc
  - name: "vmess_ws"
    type: vmess
    server: {{ conf.user.domain }}
    port: 443
    uuid: {{ conf.user.vmess }}
    alterId: 0
    cipher: none
    udp: true
    tls: true
    client-fingerprint: chrome
    servername: {{ conf.user.domain }}
    network: ws
    ws-opts:
      path: /skvws
      headers:
        Host: {{ conf.user.domain }}
  - name: "trojan_tcp"
    type: trojan
    server: {{ conf.user.domain }}
    port: 443
    password: {{ conf.user.trojan }}
    client-fingerprint: chrome
    udp: true
    sni: {{ conf.user.domain }}
  - name: "trojan_grpc"
    server: {{ conf.user.domain }}
    port: 443
    type: trojan
    password: {{ conf.user.trojan }}
    network: grpc
    sni: {{ conf.user.domain }}
    udp: true
    grpc-opts:
      grpc-service-name: sktrojangrpc
  - name: "vless_reality_vision"
    type: vless
    server: {{ conf.user.domain }}
    port: 443
    uuid: {{ conf.user.vless }}
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: {{ conf.user.domain }}
    reality-opts:
      public-key: {{ conf.user.pbk }}
      short-id: {{ conf.user.sid }}
    client-fingerprint: chrome
  - name: "vless_reality_grpc"
    type: vless
    server: {{ conf.user.domain }}
    port: 443
    uuid: {{ conf.user.vless }}
    network: grpc
    tls: true
    udp: true
    servername: {{ conf.user.domain }}
    reality-opts:
      public-key: {{ conf.user.pbk }}
      short-id: {{ conf.user.sid }}
    grpc-opts:
      grpc-service-name: "grpc"
    client-fingerprint: chrome

proxy-groups:
  - name: 手动切换
    type: select
    proxies:
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 36000
    tolerance: 50
    proxies:
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: 全球代理
    type: select
    proxies:
      - 手动切换
      - 自动选择
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: 流媒体
    type: select
    proxies:
      - 手动切换
      - 自动选择
      - DIRECT
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: DNS_Proxy
    type: select
    proxies:
      - 自动选择
      - DIRECT
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: Telegram
    type: select
    proxies:
      - 手动切换
      - 自动选择
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: Google
    type: select
    proxies:
      - 手动切换
      - 自动选择
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: YouTube
    type: select
    proxies:
      - 手动切换
      - 自动选择
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: Netflix
    type: select
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: Spotify
    type: select
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
      - DIRECT
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: HBO
    type: select
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: Bing
    type: select
    proxies:
      - 自动选择
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: OpenAI
    type: select
    proxies:
      - 自动选择
      - 手动切换
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: Disney
    type: select
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: GitHub
    type: select
    proxies:
      - 手动切换
      - 自动选择
      - DIRECT
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: 国内媒体
    type: select
    proxies:
      - DIRECT
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: 本地直连
    type: select
    proxies:
      - DIRECT
      - 自动选择
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
  - name: 漏网之鱼
    type: select
    proxies:
      - DIRECT
      - 手动切换
      - 自动选择
      - vless_tcp_vision
      - vless_ws
      - vless_grpc
      - vmess_ws
      - trojan_tcp
      - trojan_grpc
      - vless_reality_vision
      - vless_reality_grpc
rule-providers:
  lan:
    type: http
    behavior: classical
    interval: 86400
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
    path: ./Rules/lan.yaml
  reject:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
  Disney:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml
    path: ./ruleset/disney.yaml
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml
    path: ./ruleset/netflix.yaml
    interval: 86400
  YouTube:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
    path: ./ruleset/youtube.yaml
    interval: 86400
  HBO:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.yaml
    path: ./ruleset/hbo.yaml
    interval: 86400
  OpenAI:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/openai.yaml
    interval: 86400
  Bing:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml
    path: ./ruleset/bing.yaml
    interval: 86400
  Google:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
    path: ./ruleset/google.yaml
    interval: 86400
  GitHub:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
    path: ./ruleset/github.yaml
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml
    path: ./ruleset/spotify.yaml
    interval: 86400
  ChinaMaxDomain:
    type: http
    behavior: domain
    interval: 86400
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml
    path: ./Rules/ChinaMaxDomain.yaml
  ChinaMaxIPNoIPv6:
    type: http
    behavior: ipcidr
    interval: 86400
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_IP_No_IPv6.yaml
    path: ./Rules/ChinaMaxIPNoIPv6.yaml
rules:
  - RULE-SET,YouTube,YouTube,no-resolve
  - RULE-SET,Google,Google,no-resolve
  - RULE-SET,GitHub,GitHub
  - RULE-SET,telegramcidr,Telegram,no-resolve
  - RULE-SET,Spotify,Spotify,no-resolve
  - RULE-SET,Netflix,Netflix
  - RULE-SET,HBO,HBO
  - RULE-SET,Bing,Bing
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,Disney,Disney
  - RULE-SET,proxy,全球代理
  - RULE-SET,gfw,全球代理
  - RULE-SET,applications,本地直连
  - RULE-SET,ChinaMaxDomain,本地直连
  - RULE-SET,ChinaMaxIPNoIPv6,本地直连,no-resolve
  - RULE-SET,lan,本地直连,no-resolve
  - GEOIP,CN,本地直连
  - MATCH,漏网之鱼
